### ISSUE TITLE
Zenodo DOI

### ISSUE THREAD

**Issue by johnsolk** [dib-lab/2018-paper-reanalysis-op-ed#5]
We have several DOI from Zenodo. Which DOI should we be sharing in the paper? 

Note that in the past year since we started using Zenodo, DOI are now versioned. The same DOI is kept each time new files are uploaded, modified with a "Version 2".

Code (from dib-lab account on GitHub): 

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.249982.svg)](https://doi.org/10.5281/zenodo.249982)

All MMETSP data sets (.zip files of each data type):

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.257410.svg)](https://doi.org/10.5281/zenodo.257410)

Individual re-assemblies. We're on version 2 because we improved ~30 assemblies towards the end of the paper revisions:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1212585.svg)](https://doi.org/10.5281/zenodo.1212585)

Quant files:
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.257145.svg)](https://doi.org/10.5281/zenodo.257145)

Translated peptides:
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.257026.svg)](https://doi.org/10.5281/zenodo.257026)

gff3 annotations:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.255699.svg)](https://doi.org/10.5281/zenodo.255699)

Annotation name tables:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.293722.svg)](https://doi.org/10.5281/zenodo.293722)

**Comment by halexand** [comment]
Hm, I think we can just footnote that each data type gets assigned its own DOI. And then link to the individual assemblies.

**Comment by johnsolk** [comment]
Footnotes with all DOI sound good!

**Comment by johnsolk** [comment]
Update: these are the DOI to use, representing all versions of each data product set we have:

Code (from dib-lab account on GitHub): 

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.594854.svg)](https://doi.org/10.5281/zenodo.594854)

All MMETSP data sets (.zip files of each data type):

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.746048.svg)](https://doi.org/10.5281/zenodo.746048)

Individual re-assemblies. We're on version 2 because we improved ~30 assemblies towards the end of the paper revisions:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.740440.svg)](https://doi.org/10.5281/zenodo.740440)

Quant files:
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.746294.svg)](https://doi.org/10.5281/zenodo.746294)

Translated peptides:
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.745633.svg)](https://doi.org/10.5281/zenodo.745633)

gff3 annotations:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.744702.svg)](https://doi.org/10.5281/zenodo.744702)

Annotation name tables:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.775129.svg)](https://doi.org/10.5281/zenodo.775129)

**Comment by halexand** [comment]
Added the individual dois to footnote.
